<a href="https://colab.research.google.com/github/jessiepedi/IS_4487_Tokyo/blob/main/AI_Data_Prep_Explore_JessiePerezDiaz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Project: Data Preparation and Exploration

In [1]:
import pandas as pd

In [2]:
ai = pd.read_csv("https://raw.githubusercontent.com/jefftwebb/IS_4487_Tokyo/main/adviseinvest.csv")

In [3]:
ai.describe()

,answered,income,female,age,job,num_dependents,rent,own_res,new_car,chk_acct,sav_acct,num_accts,mobile,product
count,29504.000000,29504.000000,29504.000000,29504.000000,29504.000000,29504.000000,29504.000000,29504.000000,29502.000000,29504.000000,29504.000000,29504.000000,29504.000000,29504.000000
mean,0.546638,33766.893303,0.054230,34.770065,1.915401,1.140998,0.210412,0.681128,0.240797,1.468547,0.956616,2.458175,0.091106,1.535792
std,0.497829,29379.202710,0.226475,11.355777,0.658183,0.348025,0.407608,0.466047,0.427575,1.234727,1.483946,19.497353,0.287765,1.625916
min,0.000000,-65600.000000,0.000000,19.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,13550.000000,0.000000,26.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
50%,1.000000,23310.000000,0.000000,32.000000,2.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,1.000000
75%,1.000000,41690.000000,0.000000,40.000000,2.000000,1.000000,0.000000,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,3.000000
max,1.000000,159450.000000,1.000000,74.000000,3.000000,2.000000,1.000000,1.000000,1.000000,3.000000,4.000000,3345.000000,1.000000,4.000000

In [8]:
ai.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29504 entries, 0 to 29503
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   answered        29504 non-null  int64
 1   income          29504 non-null  int64
 2   female          29504 non-null  int64
 3   age             29504 non-null  int64
 4   job             29504 non-null  int64
 5   num_dependents  29504 non-null  int64
 6   rent            29504 non-null  int64
 7   own_res         29504 non-null  int64
 8   new_car         29502 non-null  float64
 9   chk_acct        29504 non-null  int64
 10  sav_acct        29504 non-null  int64
 11  num_accts       29504 non-null  int64
 12  mobile          29504 non-null  int64
 13  product         29504 non-null  int64
dtypes: float64(1), int64(13)
memory usage: 3.2 MB

In [4]:
ai.head()

,answered,income,female,age,job,num_dependents,rent,own_res,new_car,chk_acct,sav_acct,num_accts,mobile,product
0,1,13520,0,23,0,1,1,0,0.0,0,2,0,1,2
1,0,14780,0,22,2,1,0,1,0.0,3,0,3,0,0
2,1,37570,0,62,2,1,0,0,1.0,3,0,4,0,4
3,0,12450,0,33,2,1,0,1,0.0,1,0,2,0,0
4,0,12400,0,48,1,2,0,0,1.0,2,1,4,0,0

In [6]:
ai.tail()

,answered,income,female,age,job,num_dependents,rent,own_res,new_car,chk_acct,sav_acct,num_accts,mobile,product
29499,1,11630,0,44,2,1,0,1,1.0,3,2,2,0,4
29500,0,28640,0,34,1,2,0,1,0.0,2,0,2,0,0
29501,1,34480,0,74,1,1,0,1,0.0,3,0,3,0,4
29502,1,10550,0,30,2,1,0,1,1.0,3,0,1,0,1
29503,0,125790,0,44,3,1,0,0,0.0,1,0,4,1,0

# BULLET POINT 1: Remove rows with NAs

In [9]:
ai.isna().sum()

answered          0
income            0
female            0
age               0
job               0
num_dependents    0
rent              0
own_res           0
new_car           2
chk_acct          0
sav_acct          0
num_accts         0
mobile            0
product           0
dtype: int64

In [10]:
ai = ai.dropna()
ai.isna().sum()

answered          0
income            0
female            0
age               0
job               0
num_dependents    0
rent              0
own_res           0
new_car           0
chk_acct          0
sav_acct          0
num_accts         0
mobile            0
product           0
dtype: int64

# BULLET POINT 2 & 3: Remove the row with the single outlier in num_accts. Filter with a logical condition. Remove the rows with negative income values. Filter with a logical condition.

In [11]:
ai.describe()

,answered,income,female,age,job,num_dependents,rent,own_res,new_car,chk_acct,sav_acct,num_accts,mobile,product
count,29502.000000,29502.000000,29502.000000,29502.000000,29502.000000,29502.000000,29502.000000,29502.000000,29502.000000,29502.000000,29502.000000,29502.000000,29502.000000,29502.000000
mean,0.546607,33767.355434,0.054234,34.769304,1.915396,1.141007,0.210426,0.681106,0.240797,1.468443,0.956410,2.458172,0.091079,1.535794
std,0.497831,29380.091126,0.226482,11.355114,0.658205,0.348035,0.407618,0.466056,0.427575,1.234704,1.483785,19.498014,0.287726,1.625966
min,0.000000,-65600.000000,0.000000,19.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,13550.000000,0.000000,26.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
50%,1.000000,23310.000000,0.000000,32.000000,2.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,1.000000
75%,1.000000,41690.000000,0.000000,40.000000,2.000000,1.000000,0.000000,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,3.000000
max,1.000000,159450.000000,1.000000,74.000000,3.000000,2.000000,1.000000,1.000000,1.000000,3.000000,4.000000,3345.000000,1.000000,4.000000

In [12]:
ai_clean = ai[(ai['income'] > 0) &
              (ai['num_accts'] < 10)]

In [13]:
ai_clean.describe()

,answered,income,female,age,job,num_dependents,rent,own_res,new_car,chk_acct,sav_acct,num_accts,mobile,product
count,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000,29499.000000
mean,0.546595,33772.499407,0.054171,34.768840,1.915421,1.141022,0.210448,0.681074,0.240788,1.468355,0.956270,2.344859,0.091088,1.535747
std,0.497833,29374.485379,0.226359,11.354486,0.658216,0.348050,0.407634,0.466068,0.427569,1.234700,1.483765,1.200390,0.287739,1.625958
min,0.000000,2760.000000,0.000000,19.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,13550.000000,0.000000,26.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000
50%,1.000000,23310.000000,0.000000,32.000000,2.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,2.000000,0.000000,1.000000
75%,1.000000,41690.000000,0.000000,40.000000,2.000000,1.000000,0.000000,1.000000,0.000000,3.000000,2.000000,3.000000,0.000000,3.000000
max,1.000000,159450.000000,1.000000,74.000000,3.000000,2.000000,1.000000,1.000000,1.000000,3.000000,4.000000,4.000000,1.000000,4.000000

# BULLET POINT 4: Make the 4 variables you have identified in the previous question into categorical variables.

In [18]:
ai_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29499 entries, 0 to 29503
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   answered        29499 non-null  int64
 1   income          29499 non-null  int64
 2   female          29499 non-null  int64
 3   age             29499 non-null  int64
 4   job             29499 non-null  category
 5   num_dependents  29499 non-null  int64
 6   rent            29499 non-null  int64
 7   own_res         29499 non-null  int64
 8   new_car         29499 non-null  float64
 9   chk_acct        29499 non-null  category
 10  sav_acct        29499 non-null  category
 11  num_accts       29499 non-null  int64
 12  mobile          29499 non-null  int64
 13  product         29499 non-null  category
dtypes: category(4), float64(1), int64(9)
memory usage: 2.6 MB

In [19]:
ai_clean['job'] = ai_clean['job'].astype('category')
ai_clean['product'] = ai_clean['product'].astype('category')
ai_clean['chk_acct'] = ai_clean['chk_acct'].astype('category')
ai_clean['sav_acct'] = ai_clean['sav_acct'].astype('category')

<ipython-input-19-3cbb5689e4b9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ai_clean['job'] = ai_clean['job'].astype('category')
<ipython-input-19-3cbb5689e4b9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ai_clean['product'] = ai_clean['product'].astype('category')
<ipython-input-19-3cbb5689e4b9>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ai_clean['chk_acct'] = ai_clean['chk_acct'].astype('category')
<ipython-input-19-3cbb5689e4b9>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ai_clean['sav_acct'] = ai_clean['sav_acct'].astype('category')

In [20]:
ai_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29499 entries, 0 to 29503
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   answered        29499 non-null  int64
 1   income          29499 non-null  int64
 2   female          29499 non-null  int64
 3   age             29499 non-null  int64
 4   job             29499 non-null  category
 5   num_dependents  29499 non-null  int64
 6   rent            29499 non-null  int64
 7   own_res         29499 non-null  int64
 8   new_car         29499 non-null  float64
 9   chk_acct        29499 non-null  category
 10  sav_acct        29499 non-null  category
 11  num_accts       29499 non-null  int64
 12  mobile          29499 non-null  int64
 13  product         29499 non-null  category
dtypes: category(4), float64(1), int64(9)
memory usage: 2.6 MB

# Calculate and report the mean of "answered" after cleaning the dataset.  Because "answered" is coded 0/1 this is as simple as calculating the proportion of 1s in that series with .mean().

In [32]:
mean_answered = ai_clean['answered'].mean()*100
print(mean_answered)

54.65947998237228